name: GitHub Pages

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # gh-pages ブランチへ push するため
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'         # pip の依存を自動キャッシュ（actions/cache は不要）

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Checkout MatDNF (private)
        uses: actions/checkout@v4
        with:
          repository: kojima-r/MatDNF
          path: MatDNF
          token: ${{ secrets.GH_PAT }}  # PAT（Contents: Read）
      - name: Install MatDNF from local path
        run: |
          python -m pip install ./MatDNF
      - name: Install Sphinx deps
        run: python -m pip install sphinx-autoapi pydata-sphinx-theme

      - name: Build docs
        run: sphinx-build -M html docs/source docs/build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
